import React from 'react';
import TabletComponent from './tablet/tablet_profile';
import TabletComponentProfile from './tablet/tablet_profile2';
import TabletComponentProfile2 from './tablet/tablet_profile3';
import TabletComponentNumbers from './tablet/tablet_number';
import Login from './forms/login_form';
import LoginForgot from './forms/forgot_form';
import RegistrationAgreement from './forms/registration_agreement';
import RegestrationForm2 from './forms/regestrationV2';
import RegestrationForm2Location from './forms/registrationV2_location';
import RegestrationFormLocation2 from './forms/registrationV2_location2';
import RegestrationFormInvite from './forms/registrationV2_invite';
import RegestrationFormInvite2 from './forms/registrationV2_invite2';
import RegestrationFormAvailability from './forms/registrationV2_availability';
import RegestrationFormFinish from './forms/registrationV2_finish';
import FormRegistration from './forms/registration_form';
import Header from './header/header_main';
import LoginReset from './forms/reset_form';
import ModalWindow from './modal/modal';
import ModalWindowDelete from './modal/modal_delete';
import ModalWindowDeleteCheck from './modal/modal_delete2';
import ModalWindowDeleteCheck2 from './modal/modal_delete3';
import ModalWindowDeleteScroll from './modal/modal_delete_scroll';
import ModalWindowConnection from './modal/modal_connection';
import ModalWindowDeleteLoader from './modal/modal_loader';
import ModalWindowEmployee from './modal/modal_add_employee';
import ModalSelectOption from './modal/modal_select_option';
import ModalDateRequest from './modal/modal_date_request';
import ModalChangePassword from './modal/modal_chnage_password2';
import ModalChangePasswordSend from './modal/modal_change_password3';
import ModalReport from './modal/modal_report';
import ModalProfileTimeCard from './modal/modal_profile_time_card';
import ModalProfileTimeView from './modal/modal_profile_time_card_view';
import ModalWindowAfterSubmit from './modal/modal_profile_time_after_submit';
import ModalChnagePassword from './modal/modal_change_password';
import ModalHolidayReview from './modal/modal_holiday_review';
import ModalHolidayAddComment from './modal/modal_holiday_add_comment';
import ModalHolidayWaitin from './modal/modal_holiday_waiting';
import ModalHolidayOffRequest from './modal/modal_holiday_off_request';
import ModalHolidayOffView from './modal/modal_holiday_off_view';
import ModalHolidayRequestAfter from './modal/modal_holiday_request_after';
import ModalEditShift from './modal/modal_edit_shift';
import ModalEditDepartments from './modal/modal_edit_departments';
import ModalPanelAdd from './modal/modal_panel_add';
import ModalPanelAddError from './modal/modal_panel_add_error';
import ModalPanelAddError2 from './modal/modal_panel_add_error2';
import ModalPanelAbscence from './modal/modal_panel_abscence';
import ModalPanelLocation from './modal/modal_panel_location';
import ModalEdiBank from './modal/modal_edit_bank';
import ModalPanelShift from './modal/modal_panel_shift';
import ModalTablet from './modal/modal_tablet';
import EployeeAdd from './employee/employee_add';
import EployeeAdd2 from './employee/employee_add2';
import EmployeeProfileCalendar from './employee/employee_profile_calendar';
import EmployeeProfileCalendar2 from './employee/employee_profile_calendar2';
import EployeeForm from './employee/employee_form';
import EmployeeCalendar from './employee/employee_calendar';
import EployeeSetting from './employee/employee_settings';
import EployeePanelHoliday from './employee/employee_panel_holiday';
import EmployeeSettingPanel from './employee/employee_settings_panel';
import EmployeeSettingPanel2 from './employee/employee_settings_panel2';
import EmployeeSettingPanel3 from './employee/employee_settings_panel3';
import EmployeeProfileTime from './employee/employee_profile_time';
import EployeeTimeView from './employee/employee_time_view';
import EployeeGeneralHoliday from './employee/employee_general_settings';
import DashboardSetupGuide from './employee/dashboard_setup_guide';
import DashboardSetupGuide2 from './employee/dashboard_setup_guide2';
import EmployeeSettingsUser from './employee/employee_settings_user';
import EmployeeSettingsUser2 from './employee/employee_settings_user2';
import EployeeVisitor from './employee/employee_visitor';
import EmployeeVisitorProfile from './employee/employee_visitor_profile';
import {Container} from 'semantic-ui-react';

class App extends React.Component {
    render() {
     return (<EmployeeVisitorProfile/>)
    }
}

export default App;
